hash-format = "sha256"

[[files]]
file = "mods/BetterThanMending-2.2.5.pw.toml"
hash = "2f11a627a37be9144d5c0cd78761225efd4191197ea15b02a7e801bc60aa1d6f"
metafile = true

[[files]]
file = "mods/bettercommandblockui-0.5.3-1.21.7.pw.toml"
hash = "39b538ef4c8dc4caf2e1c74cd9e62cabb8ee1185213ddb7b8583af1f0cfd3b91"
metafile = true

[[files]]
file = "mods/nemos-mending-Fabric-1.21.8-1.1.2.pw.toml"
hash = "7d65a6ba807333e553d9f9ca17346919ff65b0a7228defcd72fed8d80de7a47d"
metafile = true
