hash-format = "sha256"

[[files]]
file = "mods/PlayerAnimationLibFabric-1.1.2+mc.1.21.8.pw.toml"
hash = "e5d0a59caa93e85dcb303ed5b4c2c6930534e775bfce74c6301f6463013a4cf7"
metafile = true

[[files]]
file = "mods/betterbeaconplacement-1.21.8-3.5.pw.toml"
hash = "56bab8a2221f9c0e8483993f4b02c8970499ee96f08bc7136465d69dc5bd9f26"
metafile = true

[[files]]
file = "mods/betterbooks-fabric-1.21.8-1.0.3.pw.toml"
hash = "b1298a5abb7bd57e78fbe2e2b27fa6e36ee999ffb1b15e42178ce94ba6a3f1bc"
metafile = true

[[files]]
file = "mods/bettercombat-fabric-3.0.0+1.21.8.pw.toml"
hash = "944e06961cfe16497f359d675317007fbe153b4eccca6ea75e52f743e737506d"
metafile = true

[[files]]
file = "mods/betterstats-4.0.0+fabric-1.21.8.pw.toml"
hash = "4b6518fcdba89d445a7f5734b89fe5503f368380c8ac7fbe54a245805d7a172f"
metafile = true

[[files]]
file = "mods/tcdcommons-4.0.1+fabric-1.21.8.pw.toml"
hash = "c23c6c14f63105154f2c5ab0b942db8a3adbaf10000ea3dd0d74081bba0c6242"
metafile = true
