hash-format = "sha256"

[[files]]
file = "mods/Essential_1-3-10-4_fabric_1-21-8.pw.toml"
hash = "3e9d26a1dbad738c7368fe95874573c8e1e2926eaa209159f83611d1e4861d85"
metafile = true

[[files]]
file = "resourcepacks/32x Shaded Font 1.20.4+.pw.toml"
hash = "27d1c779d178c61475a4a8ee463cda034bd8d4adcbf0d63e1f10e8a82580c008"
metafile = true

[[files]]
file = "resourcepacks/FreshAnimations_v1.10.3.pw.toml"
hash = "e8c422a514c77be23765424375e64a42bd3a7c95dca2e3634baae7947ed89674"
metafile = true

[[files]]
file = "shaderpacks/ComplementaryUnbound_r5.6.1.pw.toml"
hash = "088cfb6e427943245cbda7b6de3fb9cc43f88b91e8d976c038c288c151e70877"
metafile = true
