hash-format = "sha256"

[[files]]
file = "overrides/resourcepacks/Icons v.1.12.1.zip.rpo"
hash = "8d9e20e22692b326cc6a56d7f25f60148bcc46432ea94a460f6771cd4eb83818"

[[files]]
file = "overrides/resourcepacks/Reforged Boss Bars v1.0.zip"
hash = "7fd779653eb674e67ead21cf8a2a07c27de1f06e798c65497b3c91a385898810"

[[files]]
file = "overrides/resourcepacks/Unique Dark - Full - 1.20.2-1.21.x.zip"
hash = "45217efed8050a468fc1eb8d4e5d6e6b315686433bd181094a816e5929d07975"

[[files]]
file = "resourcepacks/AL's Enderman Revamped+FA 1.3.4.pw.toml"
hash = "4e59a6c732860d5c4f5fe66de37af1038757dd87322684e2ee6fd59a291d01b6"
metafile = true

[[files]]
file = "resourcepacks/AL's Piglins Revamped+FA 1.1.3.pw.toml"
hash = "7a443a8488a7049c0788b25ccefb535f245155e04694dd336d823c04ab5edc10"
metafile = true

[[files]]
file = "resourcepacks/AL's Skeletons Revamped+FA 1.5.3.pw.toml"
hash = "3826af866ea6ead1d2d3733ac4fc5aaa5c1de7faf2fcd3e2f96ad058fd8eda96"
metafile = true

[[files]]
file = "resourcepacks/AL's Spiders Revamped+FA 1.5.pw.toml"
hash = "99a95890c1e41cf5ad61cc7fbc11cad9ff2e9bb8a5f1413455aeed00a93cda19"
metafile = true

[[files]]
file = "resourcepacks/AL's Zombies Revamped+FA 1.4.1.pw.toml"
hash = "dad85bf1dca6968648495f32b4957279dff9e1fa8d77ce9548328382cb0d39e9"
metafile = true

[[files]]
file = "resourcepacks/Assorted Allays x FA - V.10.2.pw.toml"
hash = "e9e9f8433b40b6a39f860ae028813fe904ced618743edd54235ba08da13b5cd7"
metafile = true

[[files]]
file = "resourcepacks/Beautiful Enchanted Books - MC 1.21.10 - 8.0.0.pw.toml"
hash = "3f684291ebdb8f0446c75b3ef25e6f28feca842a984450ab2f6ba9fd07cc4f93"
metafile = true

[[files]]
file = "resourcepacks/DetailedAnimationsReworked - V1.15 PATCH.pw.toml"
hash = "dd12a256e869339c8a7686c2cc188b5a8442b1b4528174eaa9df63592a7909e9"
metafile = true

[[files]]
file = "resourcepacks/FA+All_Extensions-v1.7.pw.toml"
hash = "d40e1dc5b1cb798bce63049e2ae05d134482194abefbe9559efb95b1238be7eb"
metafile = true

[[files]]
file = "resourcepacks/FA+Details-v2.1.pw.toml"
hash = "0ee4a3c7f642d34848fe163b0d39ed43934ff5a005a98febb44568d3e7fa3e23"
metafile = true

[[files]]
file = "resourcepacks/FA+Emissive-v1.4.1.pw.toml"
hash = "27b74a290d3a083a7d412317db85c0a37061149ac3e480e4d6766f99ddc6a360"
metafile = true

[[files]]
file = "resourcepacks/FA+Objects-v2.1.pw.toml"
hash = "596be10a05b9d9b738199a0f51eb5efced6e05c42283fa8e6606598413d728dc"
metafile = true

[[files]]
file = "resourcepacks/FA+Spiders-v2.1.pw.toml"
hash = "d2c987071250f1d2163fb91e2b4c91518dc46659c39180734461e57c63139a31"
metafile = true

[[files]]
file = "resourcepacks/Fancy_Beds-v4.1.pw.toml"
hash = "5c8c14e0e683b8fd33f2bd3ff33d72fb969e84cc8e096f57a1bb7fb644dff172"
metafile = true

[[files]]
file = "resourcepacks/Fresh Buckets 1.1.2.pw.toml"
hash = "49f4952ad1deb63a84946ff0596cfde5cadb5e19d6d164a0577f1e61f0f365b1"
metafile = true

[[files]]
file = "resourcepacks/FreshAnimations_v1.10.3.pw.toml"
hash = "e8c422a514c77be23765424375e64a42bd3a7c95dca2e3634baae7947ed89674"
metafile = true

[[files]]
file = "resourcepacks/Icons v.1.12.1.pw.toml"
hash = "84f15e9c074cf460da032a0302d4088496e1852af5100427aef3395ef547ca24"
metafile = true

[[files]]
file = "resourcepacks/Lively Turtle Helmet.pw.toml"
hash = "14b76b938fcfdb4a8f684422810721ece5a0a7565bc7a70e46e810c6fb468c18"
metafile = true

[[files]]
file = "resourcepacks/Stellarity-5.2.0-RP.pw.toml"
hash = "efb2706358c6e627514c4f98c5ed4c0c80afa48b5b55bfe0d568c022b75e913f"
metafile = true

[[files]]
file = "resourcepacks/Tender Dragon v1.5.pw.toml"
hash = "6378570daf3a480e5af8095c1d599fede660aeda60dcfd2f22257c28c81647bf"
metafile = true

[[files]]
file = "resourcepacks/animated-items-1.21.7-8 - 1.5.3.pw.toml"
hash = "09d3e5efa1fe7978d540082e478c3b76a5466cc6e6a3d1ccd0c14d5e9e665842"
metafile = true

[[files]]
file = "resourcepacks/waystones_1.21.8.pw.toml"
hash = "d095494fe6cb5930da7f8add014b31184b83a73f9f35efb93b0a6191896bf051"
metafile = true
