hash-format = "sha256"

[[files]]
file = "mods/DiagonalFences-v21.8.1-1.21.8-Fabric.pw.toml"
hash = "747b23aca1d70dd54aa9833cebaf030d49940f769c0a01ed4be9c3bd12926ef5"
metafile = true

[[files]]
file = "mods/DiagonalWalls-v21.8.1-1.21.8-Fabric.pw.toml"
hash = "67259484f144b9b4f80d65afc32d62bfc138e5c659932d1b2a9db2c7630e85a2"
metafile = true

[[files]]
file = "mods/DiagonalWindows-v21.8.1-1.21.8-Fabric.pw.toml"
hash = "44e14e13f560fcf70b88c89422f295b7bd260e4af331e9996fdb42096abedbff"
metafile = true

[[files]]
file = "mods/VillageHealthcare-1.5.0.pw.toml"
hash = "0d5eb151b02bac4f44d2705cd76c8a65b98e26e0a2ab92aa94f380434e4dfd28"
metafile = true

[[files]]
file = "mods/walljump-1.21.8-1.3.5-fabric.pw.toml"
hash = "ac04db765534bd9cd8a656e544854f27fcc93551c64a93b3117de9a97a0feac1"
metafile = true

[[files]]
file = "resourcepacks/LowOnFire v1.21.8รยง8.pw.toml"
hash = "bb7c59d286eb9216da92ab4a20a7fe928b97c1edd2004933065d39ffadf1c278"
metafile = true
