hash-format = "sha256"

[[files]]
file = "mods/AdvancedLootInfo-fabric-1.21.8-1.6.0.pw.toml"
hash = "df4b9e7bd36308e7ad0085ff527e1ac1a16a7109841e2ec92968ce1d98c6e0b0"
metafile = true

[[files]]
file = "mods/AmbientSounds_FABRIC_v6.2.2_mc1.21.8.pw.toml"
hash = "5074622af07838ff194eec82a12fddc30076bed96ffded513dc8364f42c84e29"
metafile = true

[[files]]
file = "mods/AutoPickupPlus-1.2.0-fabric-1.21.8.pw.toml"
hash = "6278149193e57e80ff56f4d3f82870cb65ebac19bd0765f38d2ff86cd985ab97"
metafile = true

[[files]]
file = "mods/BadOptimizations-2.4.1-1.21.6-21.8.pw.toml"
hash = "7bcf62efd0052754195c0f5bb2d94df85e8070842f0ced74f6aaf48774507597"
metafile = true

[[files]]
file = "mods/BetterControls-1.21.6+v1.6.1.pw.toml"
hash = "2d2e4d39c50ecaabedc0f436a6605b74cbac0253f6b78c3a4799d9743c89e628"
metafile = true

[[files]]
file = "mods/ContainerSearcher-0.3.4-beta.1+mc1.21.8.pw.toml"
hash = "3eb24727248856352299e354ea7e5cfe8c784a15aa810e44877498f3ea1bfe4a"
metafile = true

[[files]]
file = "mods/Controlling-fabric-1.21.8-26.0.3.pw.toml"
hash = "0a47d5238ac219ada2a49efa6f6d623ed987d42eb445c382db591d182cd743a2"
metafile = true

[[files]]
file = "mods/CreativeCore_FABRIC_v2.14.7_mc1.21.8.pw.toml"
hash = "68e9b7c04d555b632d5491c260321fc510b389b91968fd3ca7b44ae38756a5c1"
metafile = true

[[files]]
file = "mods/DurabilityViewer-1.21.8-1.11.1.pw.toml"
hash = "6f88b7e65dd546c309ae97701c3fa7429256782cb16004ba62db3e5fa075a394"
metafile = true

[[files]]
file = "mods/EasyAnvils-v21.8.0-1.21.8-Fabric.pw.toml"
hash = "e270884bdc340b40c5306ec32cb41cc31b167f5be07f23e2bcb8c0f22aa6d5a3"
metafile = true

[[files]]
file = "mods/EasyShulkerBoxes-v21.8.3-1.21.8-Fabric.pw.toml"
hash = "a5b4e116f2f582388c25f3fac3d06d5e77d4dff33824569651c28c10cf2ed6f9"
metafile = true

[[files]]
file = "mods/Essential_1-3-10-4_fabric_1-21-8.pw.toml"
hash = "3e9d26a1dbad738c7368fe95874573c8e1e2926eaa209159f83611d1e4861d85"
metafile = true

[[files]]
file = "mods/ForgeConfigAPIPort-v21.8.2-1.21.8-Fabric.pw.toml"
hash = "bc5166a38f035c64fe03f6e138b4dbd0ba18fbe729cfbdba72b5c22a5bfb84c0"
metafile = true

[[files]]
file = "mods/ImmediatelyFast-Fabric-1.12.4+1.21.8.pw.toml"
hash = "ff45b2bc220367d67cf6da468c3acd3dc01e1fb0e015c116ad778aa5f1a2fe74"
metafile = true

[[files]]
file = "mods/InventoryProfilesNext-fabric-1.21.6-2.2.2.pw.toml"
hash = "c719db4cd4635d0e01d494f8f339cf5d0d554db8dfa6ddefe7849f08ba0a6be0"
metafile = true

[[files]]
file = "mods/Jade-1.21.8-Fabric-19.3.2.pw.toml"
hash = "f4cc1824ef5e55abd600322d6b815be5e9365c9b2d88f22beba84a981e8ef6d6"
metafile = true

[[files]]
file = "mods/MyTotemDoll-2.3.3+1.21.8.pw.toml"
hash = "20593f478d7f904b77f205e856f0c3189cf03825307ed192ab89d273367c280e"
metafile = true

[[files]]
file = "mods/ParticleEffects-1.1.0+1.21.8+fabric.pw.toml"
hash = "02844ab5e28a548cb0478595c563bf7b43e96e0414c645d7c61ca30e9c009f35"
metafile = true

[[files]]
file = "mods/PickUpNotifier-v21.8.1-1.21.8-Fabric.pw.toml"
hash = "1cca85740b2c9caea69c132fae39c29749a73356370f96a4fbe2f209a6a4fa9b"
metafile = true

[[files]]
file = "mods/PuzzlesLib-v21.8.9-1.21.8-Fabric.pw.toml"
hash = "d4aa6a42cc9fa35a9f0660b751b4ff4050ee937f434fd4bbdd241f06c4f5038c"
metafile = true

[[files]]
file = "mods/RoughlyEnoughItems-20.0.811-fabric.pw.toml"
hash = "e3362ecc0e45e98059478f662e406d0801994b247311b00009e83703984cea37"
metafile = true

[[files]]
file = "mods/Searchables-fabric-1.21.8-1.0.2.pw.toml"
hash = "bc44b7a39d8df8c6ba00b14b64c77f8ae4af59841308c0305d6845f3de9c1a25"
metafile = true

[[files]]
file = "mods/SmoothScrollingRefurbished+1.21.6-1.4.0.pw.toml"
hash = "72d3cdecc87bf39303660400acab97717b25f1004d5df8555ab5f1201015494d"
metafile = true

[[files]]
file = "mods/SubtleEffects-fabric-1.21.6-1.13.1-hotfix.1.pw.toml"
hash = "f2dbb814ee8b2fb4a0255654ef9ceb7978701c2b45fc0ee43d4f3a551753f1b8"
metafile = true

[[files]]
file = "mods/Zoomify-2.14.6+1.21.6.pw.toml"
hash = "1af71baca2cedb16ec77642d905f0944dc20f6d49fbc1c29bae9cb4f3dc63aeb"
metafile = true

[[files]]
file = "mods/appleskin-fabric-mc1.21.6-3.0.6.pw.toml"
hash = "abde8af037723216b5aa9304d7bfe661d55164910c59e82fa8bb38d57c2b9b34"
metafile = true

[[files]]
file = "mods/architectury-17.0.8-fabric.pw.toml"
hash = "cd057800440094de16999ff9fab536b55ca6770eeb6d509d315212b36606adc8"
metafile = true

[[files]]
file = "mods/automaticdoors-1.21.8-4.9.pw.toml"
hash = "3e8272d043ae6cdf3638307cfda0f851630fe09c7e52ef7b7fa0068f77857d37"
metafile = true

[[files]]
file = "mods/autotools-fabric-3.3.4.pw.toml"
hash = "fb7f8c15a7f47779eb384323fbc08e381620afe8ec6070fd9044cc23766c22c2"
metafile = true

[[files]]
file = "mods/balm-fabric-1.21.8-21.8.10.pw.toml"
hash = "de197a07ec63ef82d67be144091be56d661e0ba02043d197e510c9b6aa47a841"
metafile = true

[[files]]
file = "mods/cardinal-components-api-7.0.0-beta.1.pw.toml"
hash = "3d87dcd6b7f5e5c2628319d7bc1f939bdcf66e93183b42d28053cbbcc6b2412e"
metafile = true

[[files]]
file = "mods/carryon-fabric-1.21.8-2.7.0.pw.toml"
hash = "98828dca492eed789040c375bca2ed0a1cd185cc4d2ae234a2ac25f3c2fcf064"
metafile = true

[[files]]
file = "mods/chat_heads-0.14.2-fabric-1.21.6.pw.toml"
hash = "313ca1c91572ff396424441695de803cf8e16661e9a0fe6f74e3926daaca3104"
metafile = true

[[files]]
file = "mods/chatanimation-1.0.7.pw.toml"
hash = "25ae47065079265bfdcb286ecc5787927e9f9adacf49871a9354caa5cc5b2e36"
metafile = true

[[files]]
file = "mods/chunkloaders-1.2.9-fabric-mc1.21.6.pw.toml"
hash = "7bbed5f44b39ae88537860c7a3336893f371d9be6e61329f1c9c2dbbeb60a507"
metafile = true

[[files]]
file = "mods/cicada-lib-0.14.3+1.21.6-1.21.8.pw.toml"
hash = "fee992a4374b3099d7cc725e787488c8582d10dd872ce5ea9115145e91e76cf5"
metafile = true

[[files]]
file = "mods/clickthrough-plus-fabric-3.5.1+1.21.4.pw.toml"
hash = "ac6eb1bfedc4a9b8cd77b9a0bcf9dc9b387d716631784a3b0c410ed01a960fe0"
metafile = true

[[files]]
file = "mods/cloth-config-19.0.147-fabric.pw.toml"
hash = "25814cec4cf16d3a42d1e48f4b61afd70cabcef39f05d045e999d54252cabb22"
metafile = true

[[files]]
file = "mods/collective-1.21.8-8.11.pw.toml"
hash = "d36f9892e59f39982654adc6bd3a551e5349134622f44aa220d9e59fb2e939bc"
metafile = true

[[files]]
file = "mods/connectiblechains-2.5.4+1.21.8.pw.toml"
hash = "faf29ffaf7097890a798e8ddc3538d5e08c9798c67245ea484b1c4f7a9a2657c"
metafile = true

[[files]]
file = "mods/controlify-2.5.0+1.21.8-fabric.pw.toml"
hash = "e587bef558040e2ace5cec14d1f753fae60927ed53d6e4aa95a6bced61d88c57"
metafile = true

[[files]]
file = "mods/cullleaves-fabric-4.1.1+1.21.8.pw.toml"
hash = "01156bace51587475aafea0f04d0531e6fe52d36a66114d2bf4609fd1c9f439e"
metafile = true

[[files]]
file = "mods/dark-loading-screen-1.6.17.pw.toml"
hash = "97eaeb4e1f2b31b53693e60ec2118e93c194250f35bd89e8a08118580bf6b43a"
metafile = true

[[files]]
file = "mods/deathbackup-1.21.8-3.5.pw.toml"
hash = "5d4e76eadfc1f77f55f81069619ea7001a8385a62fb38559e1c1b12d8d510d65"
metafile = true

[[files]]
file = "mods/do_a_barrel_roll-fabric-3.8.3+1.21.6.pw.toml"
hash = "92d6f7623d1eb103a108f31535d2df9836db7c628981599b75c2b5d3983710fc"
metafile = true

[[files]]
file = "mods/dynamic-fps-3.11.0+minecraft-1.21.6-fabric.pw.toml"
hash = "c70d626a465b66734f69df9ec8b9e3f11606b860ef4e3b567843781b6ec2a177"
metafile = true

[[files]]
file = "mods/entityculling-fabric-1.9.4-mc1.21.8.pw.toml"
hash = "bc05660579dac488eeb9064cb446ffb6eb42717f2fae5e4f6e401fa7643f6d21"
metafile = true

[[files]]
file = "mods/fabric-api-0.136.1+1.21.8.pw.toml"
hash = "66956601c9d734d338a36eb398875781c5626c6577ada3d129b965ad61b460e8"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin-1.13.8+kotlin.2.3.0.pw.toml"
hash = "7292f44d37ab4318ccbe63aca26d4d033ca3c85762c1c3dad9dc0dacdce30d2e"
metafile = true

[[files]]
file = "mods/fabric-permissions-api-0.4.0.pw.toml"
hash = "c373968ef084819ce445f9579887fe12a8cd4d67a6ea858b8c88430d0b6c7db4"
metafile = true

[[files]]
file = "mods/fallingleaves-2.0.1+1.21.5.pw.toml"
hash = "d9c97e82b470a29d5f1854709e8bd16b1ef576e28b72ce9aca379aeb4e800a0c"
metafile = true

[[files]]
file = "mods/fconfiglib-1.1.1.pw.toml"
hash = "a6ca5fd8a38c776ffa7c13e58377310289a7a3eae5e36327a29cae467e1feb7c"
metafile = true

[[files]]
file = "mods/ferritecore-8.0.0-fabric.pw.toml"
hash = "dca786e9393faa2f66aae0ef3091223ad8d5adb42164c81878cd1da866d1bf3e"
metafile = true

[[files]]
file = "mods/freecam-fabric-1.3.4+mc1.21.6.pw.toml"
hash = "d11b77726aed9494b954ae9e7d098c8256da8aad4e975a308703b359a8bf5c4d"
metafile = true

[[files]]
file = "mods/frostiful-2.2.8+1.21.8.pw.toml"
hash = "74e035c82cdc9d4804d017d2227ceba3c7cb746e6e467657fb3c39b21991e7d6"
metafile = true

[[files]]
file = "mods/fzzy_config-0.7.4-fix1+1.21.6.pw.toml"
hash = "0e75687c46e10abb0a6db7b606f38a800f69fe2b5f88e5adc07884d5c9082dd0"
metafile = true

[[files]]
file = "mods/globalnarrationtoggle-1.21.8-1.4.pw.toml"
hash = "b267379c27c1c0b7191f5c5bc2f3f5176d7f28a4a94bf28f05f8af36be4d43ab"
metafile = true

[[files]]
file = "mods/graves-3.8.1+1.21.6.pw.toml"
hash = "9390aff375607b3d0dc4a38725c3c47f4987dc570806095cccb4a5c944d641a0"
metafile = true

[[files]]
file = "mods/happy-speed-1.0.1.pw.toml"
hash = "1e88204a4e9cc34ab00400f126eca1d31670bdfab4d2e0c010677d98311284b0"
metafile = true

[[files]]
file = "mods/infinitetrading-1.21.8-4.6.pw.toml"
hash = "f398c1826e491146b2f50d4deae2fdf396e89ec26e5b28574cc44b0d9dbe5344"
metafile = true

[[files]]
file = "mods/iris-fabric-1.9.6+mc1.21.8.pw.toml"
hash = "ab21d87a051b404b137365fc53edcf4b1ecdd41c9c9406c6f5ecfb4687b7d3be"
metafile = true

[[files]]
file = "mods/jamlib-fabric-1.3.5+1.21.8.pw.toml"
hash = "787b768513f421c899bac79414252a07d788ab5cf9c8d99ed092ba9a37eea8be"
metafile = true

[[files]]
file = "mods/jjelytraswap-fabric-2.3.8+1.21.8.pw.toml"
hash = "f75adfa3ac64830a29626c95039a4261e8788f44d6b8d745a17e9d513fa2ba8a"
metafile = true

[[files]]
file = "mods/journeymap-fabric-1.21.8-6.0.0-beta.52.pw.toml"
hash = "522202c0dfe211f7b8a67172c825f8e76b6bd49d53ac38124f0181783014f1b7"
metafile = true

[[files]]
file = "mods/just-hammers-fabric-21.8.3.pw.toml"
hash = "bca0a91f1d8482aae1a2f46572514a510fcbcab806bc3e5610eecb708fb39563"
metafile = true

[[files]]
file = "mods/justenoughbreeding-fabric-1.21.7-1.21.8-1.6.2.pw.toml"
hash = "05848a963af138394d2075ce4405919a78a54f0f11e411e07c09c20484ac7040"
metafile = true

[[files]]
file = "mods/lambdynamiclights-4.8.7+1.21.8.pw.toml"
hash = "42b719fad6ad09bdcd977bbcb866b1e65e1ef7424501f9b3ad2209c8bbe3fbb1"
metafile = true

[[files]]
file = "mods/libIPN-fabric-1.21.6-6.6.2.pw.toml"
hash = "4aca4518a8f84113a6d5b7374e2cf6856966b5ce9821b5fc78fe6ce6d7627ba5"
metafile = true

[[files]]
file = "mods/litematica-fabric-1.21.8-0.23.5.pw.toml"
hash = "0c6efd55db0b7ab9c78780cd2aa13ec7e3e5a92c6be76b3e230936e76fc2f7fd"
metafile = true

[[files]]
file = "mods/lithium-fabric-0.18.1+mc1.21.8.pw.toml"
hash = "80cb015075796bd117a0cf8b5707970cde3699124c22e09c98ff080adfe0817a"
metafile = true

[[files]]
file = "mods/magnetic-enchantment-v1.0.5.pw.toml"
hash = "9d4a093970bbbdf8abd012123fbdc2d63b8702fd013bbb9d79d402066cc1b496"
metafile = true

[[files]]
file = "mods/make_bubbles_pop-0.3.1-fabric-mc1.21.2-1.21.4.pw.toml"
hash = "a1b2f3e05377195bc6e7f01f4e075cdf78f38cab456b1719c07dab8756aedbe4"
metafile = true

[[files]]
file = "mods/malilib-fabric-1.21.8-0.25.6.pw.toml"
hash = "b989c3e6c6ace9bf3fd3966a1f30bf7cda4d2dc190a50e204187e3e432ee83b1"
metafile = true

[[files]]
file = "mods/mcw-doors-1.1.2-mc1.21.8fabric.pw.toml"
hash = "c1b0ed73a5b1b8896c38624ce9e2df352a1a541684bced573e03f9881d3ecb96"
metafile = true

[[files]]
file = "mods/mcw-furniture-3.4.1-mc1.21.8fabric.pw.toml"
hash = "84713d8979e3100b6a3a795a537ebd81be90e167f383135b28f8a8d60327d6df"
metafile = true

[[files]]
file = "mods/mcw-holidays-1.1.2-mc1.21.8fabric.pw.toml"
hash = "9a0883f3a9a1558afa4e6b4df65e7d48d93600cff3303c3e8a72a290429e41b7"
metafile = true

[[files]]
file = "mods/mcw-lights-1.1.5-mc1.21.8fabric.pw.toml"
hash = "b76feec4fc78f17ef9b87b7413c903ae9720617655dd4cc039c01ef65a6c9fbe"
metafile = true

[[files]]
file = "mods/mcw-mcwfences-1.2.1-mc1.21.8fabric.pw.toml"
hash = "fd171d0c77ac4eaa4f13a288217cfadd6651cc3e63d8911718a11ffecbb7d674"
metafile = true

[[files]]
file = "mods/mcw-mcwpaths-1.1.1-mc1.21.8fabric.pw.toml"
hash = "d901a82864948364db3afc832714d872f7befbc3b0532a40e51f5584f45ee3dd"
metafile = true

[[files]]
file = "mods/mcw-mcwstairs-1.0.2-mc1.21.8fabric.pw.toml"
hash = "74bafc7c6142569c95ff2140c46ef7f71478fa162edb573e57fb627858b91b4a"
metafile = true

[[files]]
file = "mods/mcw-mcwwindows-2.4.2-mc1.21.8fabric.pw.toml"
hash = "d41ea332445cd534dfe6f3adc7b8117ae3491e2b969b2ac3acf937f243b1fa73"
metafile = true

[[files]]
file = "mods/mcw-paintings-1.0.5-1.21.8fabric.pw.toml"
hash = "d47ac00cfcee3178a0443d33a844a32b6daccb85d5148a2dd490f5631868287e"
metafile = true

[[files]]
file = "mods/mcw-roofs-2.3.2-mc1.21.8fabric.pw.toml"
hash = "ee297d7174540394f4fed1dfbdc4d8d18a775eda587eeadaa099fa642cd12eec"
metafile = true

[[files]]
file = "mods/midnightlib-fabric-1.9.2+1.21.8.pw.toml"
hash = "192db8c8e9e146435b13a75e6ea3acf9bb7f32ca543790d9c9586415598d7e6d"
metafile = true

[[files]]
file = "mods/modmenu-15.0.0.pw.toml"
hash = "9dc021d3bfdb8dca90b6f7891fa79a7ff1faec63996bd97715063c1c166a29df"
metafile = true

[[files]]
file = "mods/monkey-utils-1.0.2.pw.toml"
hash = "dec7a18b21398278ead6a8510766129ac1072aa224751d1e90d6702577e2e6da"
metafile = true

[[files]]
file = "mods/moreculling-fabric-1.21.8-1.4.0-beta.2.pw.toml"
hash = "8a4b9472a78e036bb4e2ef63645e15fc72193a121c8c504186c2fe3fb12ae754"
metafile = true

[[files]]
file = "mods/placeholder-api-2.7.2+1.21.8.pw.toml"
hash = "bda9d7c0b33cf8064a9c7208d7efa5d9ba94fdba1db4617923378ca295703b26"
metafile = true

[[files]]
file = "mods/playerladder-fabric-1.21.8-0.7.3.pw.toml"
hash = "ced4ad87429489a510d6cb392471bb79f322c1e3268dc71b16f74d6795ae35f4"
metafile = true

[[files]]
file = "mods/polymer-bundled-0.13.13+1.21.8.pw.toml"
hash = "bdb802dc5ebeeb0227f543f35c5beb12300e2cd4e87336db3b0a94af64fa5d28"
metafile = true

[[files]]
file = "mods/publicenderchest-1.2.1.pw.toml"
hash = "23e6f6ba37a58eaa74c83d12010906fa569de9940eedd6d8ed4a8070837fb167"
metafile = true

[[files]]
file = "mods/reeses-sodium-options-fabric-1.8.4+mc1.21.6.pw.toml"
hash = "3b03d741aa981c0eed0d7cf952127e6ea8ce17385d18ee622dabd481c57fcc9d"
metafile = true

[[files]]
file = "mods/rei-search-bar-calculations-1.0.2+1.21.6-8.pw.toml"
hash = "884208ee4d9c02dfc5f0b6550570ad993cdba474e1b60c31e0f461d1a3c2ff9d"
metafile = true

[[files]]
file = "mods/replaymod-1.21.7-2.6.23.pw.toml"
hash = "8ac249ac868bff09b9c36fb07257066b3960b002f2ba91229c93de97fa19c30b"
metafile = true

[[files]]
file = "mods/rightclickharvest-fabric-4.6.0+1.21.8.pw.toml"
hash = "6fd72a6aed5e909392f2d936eed64bb8a99da0c4c18aa161b36d0c7e19979d81"
metafile = true

[[files]]
file = "mods/scarecrowsterritory-1.1.11-fabric-mc1.21.6.pw.toml"
hash = "566914d1a1a2660e48e1e51e1c8b9e72dbc367279edd03499da94cb386c1b4d8"
metafile = true

[[files]]
file = "mods/signed_paintings-1.2.7-mc1.21.6.pw.toml"
hash = "3d81825a40d74d714209b474b051a86c14ed463d55936fb80d38c9c03d2fca12"
metafile = true

[[files]]
file = "mods/sit-1.21.6-29.pw.toml"
hash = "a40f56ac7dcd49cfeeb6dec819ed19e34f9f994c1f3d97c6aba78fb175a2348f"
metafile = true

[[files]]
file = "mods/sodium-fabric-0.7.3+mc1.21.8.pw.toml"
hash = "7754449989161c214a6c9ac1a6ed30704d6ad3ad397821521a5d21a2140cc51b"
metafile = true

[[files]]
file = "mods/sound-physics-remastered-fabric-1.21.8-1.5.1.pw.toml"
hash = "52a8deec4fbd432e4469162217c76b09cb829db7ca34dc647c7b32befc972b6e"
metafile = true

[[files]]
file = "mods/spark-1.10.142-fabric.pw.toml"
hash = "cbe863df41eca0e881563895696ce1b600c93027ccd9338d56ab3eec924d8b2a"
metafile = true

[[files]]
file = "mods/status-effect-bars-1.0.9.pw.toml"
hash = "18991de1346f2b6dfd40b47a8a3f4cfbd8264ba723788511de245cdb6e444303"
metafile = true

[[files]]
file = "mods/supermartijn642configlib-1.1.8-fabric-mc1.21.pw.toml"
hash = "6d380228f665e7b80894cbc0b1a65030619ced6ea18e478eca50746acc0ac5eb"
metafile = true

[[files]]
file = "mods/supermartijn642corelib-1.1.18f-fabric-mc1.21.7.pw.toml"
hash = "63cb646708251890e6e3e4dc92dc96edc878912880345541f3962a22b736f0cd"
metafile = true

[[files]]
file = "mods/thermoo-7.1.1.pw.toml"
hash = "dc67ffbc011ea33a0e9f8910cc08772f9502317442b3db4c3f2a331b672ae4e7"
metafile = true

[[files]]
file = "mods/toms_storage_fabric-1.21.8-2.5.2.pw.toml"
hash = "358084c425b060c5c43882d033b907ff0357c483134746cb0bbd041247f5bb50"
metafile = true

[[files]]
file = "mods/trade-cycling-fabric-1.21.8-1.0.20.pw.toml"
hash = "59bdcb4ed334592836b366ddef6cdf312fe9078abc13452a21ee4dc300cb364d"
metafile = true

[[files]]
file = "mods/travelersbackpack-fabric-1.21.8-10.8.4.pw.toml"
hash = "65a04aa5e8d9b0d99e42fbe1b341f970c0e83acff1af1786c62850ea8b446637"
metafile = true

[[files]]
file = "mods/treeharvester-1.21.8-9.2.pw.toml"
hash = "e19bea283f8c1ca23010996b3b256591587740b973c3546d91ed30ae954b3c28"
metafile = true

[[files]]
file = "mods/voicechat-fabric-1.21.8-2.6.9.pw.toml"
hash = "1c94186f37b84cd6f4f94f2be98d3fc878af31544c04069bea556268622b6472"
metafile = true

[[files]]
file = "mods/waystones-fabric-1.21.8-21.8.5.pw.toml"
hash = "2d99d24066577077d4e25ee8df46f3eadc61933fc7bfcd4362ff418cd4579b09"
metafile = true

[[files]]
file = "mods/worldedit-mod-7.3.16.pw.toml"
hash = "d735fef9330a099ab060559733ef202c7c767fc91cdda310d18567e463023ef3"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3-3.8.1+1.21.6-fabric.pw.toml"
hash = "c3e5f06045e89444933b08821731ff0b9900b9c4df023a63edb84c4e9e9d73c9"
metafile = true

[[files]]
file = "shaderpacks/ComplementaryUnbound_r5.6.1.pw.toml"
hash = "088cfb6e427943245cbda7b6de3fb9cc43f88b91e8d976c038c288c151e70877"
metafile = true

[[files]]
file = "shaderpacks/Spooklementary_v2.0.4.pw.toml"
hash = "095c59e7a9f03a3d7585e6a4677bc30fd87e9ba96a3028ce0bdb3e390a3aef9b"
metafile = true

[[files]]
file = "shaderpacks/photon_v1.2a.pw.toml"
hash = "9804e4bcdaf69bc052bcfc12efc2e49fde3bb4b7c04864aef1c21fcf88419c83"
metafile = true
