name = "CUBITOS"
author = "Jofree"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a61f5b78093838a8ada638624d7084d5da0562cad203190997658f5f5342148c"

[versions]
fabric = "0.18.3"
minecraft = "1.21.8"
