name = "CUBITOS"
author = "Jofree"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5967cf7f167ffd326b7fd4b6102400cfaef68e57c405560a42b63abf2e6c65b9"

[versions]
fabric = "0.18.3"
minecraft = "1.21.8"
