name = "CUBITOS"
author = "Jofree"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97635b81c5bcd2e74900b2aec9026a655e5213068f3bd0cce7dc201bdd98fa2f"

[versions]
fabric = "0.18.3"
minecraft = "1.21.8"
