name = "cubitos 1.21.8"
author = "Jofree"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5544c7ff08f4a81497b33a57530b55c1142b6aaf944f53a20a1875e63377667"

[versions]
fabric = "0.18.3"
minecraft = "1.21.8"
