name = "cubitos 1.21.8"
author = "Jofree"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d042efe67bbe8a93d989d7d7515c976e9200909059a6409b01fc775213685ab9"

[versions]
fabric = "0.18.3"
minecraft = "1.21.8"
