name = "CUBITOS"
author = "Jofree"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "567cf07801018527f4ae58b2f9743f62e132baa4b90f97be8aa43ded6582ec09"

[versions]
fabric = "0.18.3"
minecraft = "1.21.8"
