name = "CUBITOS"
author = "Jofree"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faf91a4c1d19df534c42834374bc14045013345c2f057677dc8e5fe75f8f8ecf"

[versions]
fabric = "0.18.3"
minecraft = "1.21.8"
