name = "CUBITOS"
author = "Jofree"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "164823dbe1932c37854439bce10ef990afa3400b96808abfdc157bb17c65e868"

[versions]
fabric = "0.18.3"
minecraft = "1.21.8"
