name = "cubitos 1.21.8"
author = "Jofree"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "642ad3e6b115d4c184f89f4e77d0d45f80d094a82ec6b7dec56f27fa2c514191"

[versions]
fabric = "0.18.3"
minecraft = "1.21.8"
