name = "cubitos 1.21.8"
author = "Jofree"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "377d971095f3be287e4f534a52cbebebe34e49a00f1deafb8a4892c334974565"

[versions]
fabric = "0.18.3"
minecraft = "1.21.8"
