name = "CUBITOS"
author = "Jofree"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19bec886881aa4285cb98bb43d07b85059c226def1dbb68021f74cb2eca21cb8"

[versions]
fabric = "0.18.3"
minecraft = "1.21.8"
