name = "CUBITOS"
author = "Jofree"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb35957ff5e3a0459fe96163963baac12974a5528dede23f3fd038991239921f"

[versions]
fabric = "0.18.3"
minecraft = "1.21.8"
