#Add players to a blacklist to prevent them from being able to use the public ender chest.
[player_blacklist]
	#(Default = false) Toggle the use of the player blacklist feature.
	enable_player_blacklist = false
	#Add players to this blacklist by specifying their username.
	player_blacklist = []

#Add dimension identifiers to this blacklist to prevent players from being able to use the public ender chest in those dimensions.
[dimension_blacklist]
	#(Default = false) Toggle the use of the dimension blacklist feature.
	enable_dimension_blacklist = false
	#Add dimensions to this blacklist by specifying their full identifier. For example, to add the Overworld dimension, you can add the identifier "minecraft:overworld" to this list.
	dimension_blacklist = []

#Configure settings related to the mod's database.
[database]
	#(Default = 30) Purge database entries older than the amount of days specified. The database is purged on every server shutdown and using the `/publicenderchest database purge` command.
	purge_older_than_x_days = 30
